// This file is generated by the 'node-soap-servicegenerator'
// visit : https://github.com/BreeeZe/node-soap-servicegenerator for more info

var NOT_IMPLEMENTED = {
  Fault: {
    Code: {
      Value: "soap:client"
    },
    Reason: {
      Text: "Method not implemented"
    }
  }
};
var exports = module.exports = {};

exports.PTZService = {
  PTZService : {
    PTZ : {
      //var GetServiceCapabilities = { };
      GetServiceCapabilities : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetServiceCapabilitiesResponse = { 
          //Capabilities : { 
            //attributes : {
              //EFlip : {xs:boolean},
              //Reverse : {xs:boolean},
              //GetCompatibleConfigurations : {xs:boolean},
              //MoveStatus : {xs:boolean},
              //StatusPosition : {xs:boolean}
            //}
          //}
        //
        //};
        //return GetServiceCapabilitiesResponse;
      },

      //var GetNodes = { };
      GetNodes : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetNodesResponse = { 
          //PTZNode : [{ 
            //attributes : {
              //token : {tt:ReferenceToken}
            //}
          //
            //attributes : {
              //FixedHomePosition : {xs:boolean}
            //},
            //Name : { xs:string},
            //SupportedPTZSpaces : { 
              //AbsolutePanTiltPositionSpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //},
                //YRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //AbsoluteZoomPositionSpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //RelativePanTiltTranslationSpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //},
                //YRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //RelativeZoomTranslationSpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //ContinuousPanTiltVelocitySpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //},
                //YRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //ContinuousZoomVelocitySpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //PanTiltSpeedSpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //ZoomSpeedSpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //Extension : { }
            //},
            //MaximumNumberOfPresets : { xs:int},
            //HomeSupported : { xs:boolean},
            //AuxiliaryCommands : [{ xs:string}],
            //Extension : { 
              //SupportedPresetTour : { 
                //MaximumNumberOfPresetTours : { xs:int},
                //PTZPresetTourOperation : [{ xs:string}],
                //Extension : { }
              //},
              //Extension : { }
            //}
          //}]
        //
        //};
        //return GetNodesResponse;
      },

      //var GetNode = { 
        //NodeToken : { xs:string}
      //
      //};
      GetNode : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetNodeResponse = { 
          //PTZNode : { 
            //attributes : {
              //token : {tt:ReferenceToken}
            //}
          //
            //attributes : {
              //FixedHomePosition : {xs:boolean}
            //},
            //Name : { xs:string},
            //SupportedPTZSpaces : { 
              //AbsolutePanTiltPositionSpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //},
                //YRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //AbsoluteZoomPositionSpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //RelativePanTiltTranslationSpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //},
                //YRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //RelativeZoomTranslationSpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //ContinuousPanTiltVelocitySpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //},
                //YRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //ContinuousZoomVelocitySpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //PanTiltSpeedSpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //ZoomSpeedSpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //Extension : { }
            //},
            //MaximumNumberOfPresets : { xs:int},
            //HomeSupported : { xs:boolean},
            //AuxiliaryCommands : [{ xs:string}],
            //Extension : { 
              //SupportedPresetTour : { 
                //MaximumNumberOfPresetTours : { xs:int},
                //PTZPresetTourOperation : [{ xs:string}],
                //Extension : { }
              //},
              //Extension : { }
            //}
          //}
        //
        //};
        //return GetNodeResponse;
      },

      //var GetConfiguration = { 
        //PTZConfigurationToken : { xs:string}
      //
      //};
      GetConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetConfigurationResponse = { 
          //PTZConfiguration : { 
            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
            //attributes : {
              //MoveRamp : {xs:int},
              //PresetRamp : {xs:int},
              //PresetTourRamp : {xs:int}
            //},
            //NodeToken : { xs:string},
            //DefaultAbsolutePantTiltPositionSpace : { xs:anyURI},
            //DefaultAbsoluteZoomPositionSpace : { xs:anyURI},
            //DefaultRelativePanTiltTranslationSpace : { xs:anyURI},
            //DefaultRelativeZoomTranslationSpace : { xs:anyURI},
            //DefaultContinuousPanTiltVelocitySpace : { xs:anyURI},
            //DefaultContinuousZoomVelocitySpace : { xs:anyURI},
            //DefaultPTZSpeed : { 
              //PanTilt : { 
                //attributes : {
                  //x : {xs:float},
                  //y : {xs:float},
                  //space : {xs:anyURI}
                //}
              //},
              //Zoom : { 
                //attributes : {
                  //x : {xs:float},
                  //space : {xs:anyURI}
                //}
              //}
            //},
            //DefaultPTZTimeout : { xs:duration},
            //PanTiltLimits : { 
              //Range : { 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //},
                //YRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}
            //},
            //ZoomLimits : { 
              //Range : { 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}
            //},
            //Extension : { 
              //PTControlDirection : { 
                //EFlip : { 
                  //Mode : { xs:string}
                //},
                //Reverse : { 
                  //Mode : { xs:string}
                //},
                //Extension : { }
              //},
              //Extension : { }
            //}
          //}
        //
        //};
        //return GetConfigurationResponse;
      },

      //var GetConfigurations = { };
      GetConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetConfigurationsResponse = { 
          //PTZConfiguration : [{ 
            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
            //attributes : {
              //MoveRamp : {xs:int},
              //PresetRamp : {xs:int},
              //PresetTourRamp : {xs:int}
            //},
            //NodeToken : { xs:string},
            //DefaultAbsolutePantTiltPositionSpace : { xs:anyURI},
            //DefaultAbsoluteZoomPositionSpace : { xs:anyURI},
            //DefaultRelativePanTiltTranslationSpace : { xs:anyURI},
            //DefaultRelativeZoomTranslationSpace : { xs:anyURI},
            //DefaultContinuousPanTiltVelocitySpace : { xs:anyURI},
            //DefaultContinuousZoomVelocitySpace : { xs:anyURI},
            //DefaultPTZSpeed : { 
              //PanTilt : { 
                //attributes : {
                  //x : {xs:float},
                  //y : {xs:float},
                  //space : {xs:anyURI}
                //}
              //},
              //Zoom : { 
                //attributes : {
                  //x : {xs:float},
                  //space : {xs:anyURI}
                //}
              //}
            //},
            //DefaultPTZTimeout : { xs:duration},
            //PanTiltLimits : { 
              //Range : { 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //},
                //YRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}
            //},
            //ZoomLimits : { 
              //Range : { 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}
            //},
            //Extension : { 
              //PTControlDirection : { 
                //EFlip : { 
                  //Mode : { xs:string}
                //},
                //Reverse : { 
                  //Mode : { xs:string}
                //},
                //Extension : { }
              //},
              //Extension : { }
            //}
          //}]
        //
        //};
        //return GetConfigurationsResponse;
      },

      //var SetConfiguration = { 
        //PTZConfiguration : { 
          //attributes : {
            //token : {tt:ReferenceToken}
          //},
          //Name : { xs:string},
          //UseCount : { xs:int}
        //
          //attributes : {
            //MoveRamp : {xs:int},
            //PresetRamp : {xs:int},
            //PresetTourRamp : {xs:int}
          //},
          //NodeToken : { xs:string},
          //DefaultAbsolutePantTiltPositionSpace : { xs:anyURI},
          //DefaultAbsoluteZoomPositionSpace : { xs:anyURI},
          //DefaultRelativePanTiltTranslationSpace : { xs:anyURI},
          //DefaultRelativeZoomTranslationSpace : { xs:anyURI},
          //DefaultContinuousPanTiltVelocitySpace : { xs:anyURI},
          //DefaultContinuousZoomVelocitySpace : { xs:anyURI},
          //DefaultPTZSpeed : { 
            //PanTilt : { 
              //attributes : {
                //x : {xs:float},
                //y : {xs:float},
                //space : {xs:anyURI}
              //}
            //},
            //Zoom : { 
              //attributes : {
                //x : {xs:float},
                //space : {xs:anyURI}
              //}
            //}
          //},
          //DefaultPTZTimeout : { xs:duration},
          //PanTiltLimits : { 
            //Range : { 
              //URI : { xs:anyURI},
              //XRange : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //},
              //YRange : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //}
            //}
          //},
          //ZoomLimits : { 
            //Range : { 
              //URI : { xs:anyURI},
              //XRange : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //}
            //}
          //},
          //Extension : { 
            //PTControlDirection : { 
              //EFlip : { 
                //Mode : { xs:string}
              //},
              //Reverse : { 
                //Mode : { xs:string}
              //},
              //Extension : { }
            //},
            //Extension : { }
          //}
        //},
        //ForcePersistence : { xs:boolean}
      //
      //};
      SetConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetConfigurationResponse = { };
        //return SetConfigurationResponse;
      },

      //var GetConfigurationOptions = { 
        //ConfigurationToken : { xs:string}
      //
      //};
      GetConfigurationOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetConfigurationOptionsResponse = { 
          //PTZConfigurationOptions : { 
            //attributes : {
              //PTZRamps : {tt:IntAttrList}
            //},
            //Spaces : { 
              //AbsolutePanTiltPositionSpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //},
                //YRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //AbsoluteZoomPositionSpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //RelativePanTiltTranslationSpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //},
                //YRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //RelativeZoomTranslationSpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //ContinuousPanTiltVelocitySpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //},
                //YRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //ContinuousZoomVelocitySpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //PanTiltSpeedSpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //ZoomSpeedSpace : [{ 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}],
              //Extension : { }
            //},
            //PTZTimeout : { 
              //Min : { xs:duration},
              //Max : { xs:duration}
            //},
            //PTControlDirection : { 
              //EFlip : { 
                //Mode : [{ xs:string}],
                //Extension : { }
              //},
              //Reverse : { 
                //Mode : [{ xs:string}],
                //Extension : { }
              //},
              //Extension : { }
            //},
            //Extension : { }
          //}
        //
        //};
        //return GetConfigurationOptionsResponse;
      },

      //var SendAuxiliaryCommand = { 
        //ProfileToken : { xs:string},
        //AuxiliaryData : { xs:string}
      //
      //};
      SendAuxiliaryCommand : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SendAuxiliaryCommandResponse = { 
          //AuxiliaryResponse : { xs:string}
        //
        //};
        //return SendAuxiliaryCommandResponse;
      },

      //var GetPresets = { 
        //ProfileToken : { xs:string}
      //
      //};
      GetPresets : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetPresetsResponse = { 
          //Preset : [{ 
            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //PTZPosition : { 
              //PanTilt : { 
                //attributes : {
                  //x : {xs:float},
                  //y : {xs:float},
                  //space : {xs:anyURI}
                //}
              //},
              //Zoom : { 
                //attributes : {
                  //x : {xs:float},
                  //space : {xs:anyURI}
                //}
              //}
            //}
          //}]
        //
        //};
        //return GetPresetsResponse;
      },

      //var SetPreset = { 
        //ProfileToken : { xs:string},
        //PresetName : { xs:string},
        //PresetToken : { xs:string}
      //
      //};
      SetPreset : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetPresetResponse = { 
          //PresetToken : { xs:string}
        //
        //};
        //return SetPresetResponse;
      },

      //var RemovePreset = { 
        //ProfileToken : { xs:string},
        //PresetToken : { xs:string}
      //
      //};
      RemovePreset : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var RemovePresetResponse = { };
        //return RemovePresetResponse;
      },

      //var GotoPreset = { 
        //ProfileToken : { xs:string},
        //PresetToken : { xs:string},
        //Speed : { 
          //PanTilt : { 
            //attributes : {
              //x : {xs:float},
              //y : {xs:float},
              //space : {xs:anyURI}
            //}
          //},
          //Zoom : { 
            //attributes : {
              //x : {xs:float},
              //space : {xs:anyURI}
            //}
          //}
        //}
      //
      //};
      GotoPreset : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GotoPresetResponse = { };
        //return GotoPresetResponse;
      },

      //var GotoHomePosition = { 
        //ProfileToken : { xs:string},
        //Speed : { 
          //PanTilt : { 
            //attributes : {
              //x : {xs:float},
              //y : {xs:float},
              //space : {xs:anyURI}
            //}
          //},
          //Zoom : { 
            //attributes : {
              //x : {xs:float},
              //space : {xs:anyURI}
            //}
          //}
        //}
      //
      //};
      GotoHomePosition : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GotoHomePositionResponse = { };
        //return GotoHomePositionResponse;
      },

      //var SetHomePosition = { 
        //ProfileToken : { xs:string}
      //
      //};
      SetHomePosition : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetHomePositionResponse = { };
        //return SetHomePositionResponse;
      },

      //var ContinuousMove = { 
        //ProfileToken : { xs:string},
        //Velocity : { 
          //PanTilt : { 
            //attributes : {
              //x : {xs:float},
              //y : {xs:float},
              //space : {xs:anyURI}
            //}
          //},
          //Zoom : { 
            //attributes : {
              //x : {xs:float},
              //space : {xs:anyURI}
            //}
          //}
        //},
        //Timeout : { xs:duration}
      //
      //};
      ContinuousMove : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var ContinuousMoveResponse = { };
        //return ContinuousMoveResponse;
      },

      //var RelativeMove = { 
        //ProfileToken : { xs:string},
        //Translation : { 
          //PanTilt : { 
            //attributes : {
              //x : {xs:float},
              //y : {xs:float},
              //space : {xs:anyURI}
            //}
          //},
          //Zoom : { 
            //attributes : {
              //x : {xs:float},
              //space : {xs:anyURI}
            //}
          //}
        //},
        //Speed : { 
          //PanTilt : { 
            //attributes : {
              //x : {xs:float},
              //y : {xs:float},
              //space : {xs:anyURI}
            //}
          //},
          //Zoom : { 
            //attributes : {
              //x : {xs:float},
              //space : {xs:anyURI}
            //}
          //}
        //}
      //
      //};
      RelativeMove : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var RelativeMoveResponse = { };
        //return RelativeMoveResponse;
      },

      //var GetStatus = { 
        //ProfileToken : { xs:string}
      //
      //};
      GetStatus : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetStatusResponse = { 
          //PTZStatus : { 
            //Position : { 
              //PanTilt : { 
                //attributes : {
                  //x : {xs:float},
                  //y : {xs:float},
                  //space : {xs:anyURI}
                //}
              //},
              //Zoom : { 
                //attributes : {
                  //x : {xs:float},
                  //space : {xs:anyURI}
                //}
              //}
            //},
            //MoveStatus : { 
              //PanTilt : { xs:string},
              //Zoom : { xs:string}
            //},
            //Error : { xs:string},
            //UtcTime : { xs:dateTime}
          //}
        //
        //};
        //return GetStatusResponse;
      },

      //var AbsoluteMove = { 
        //ProfileToken : { xs:string},
        //Position : { 
          //PanTilt : { 
            //attributes : {
              //x : {xs:float},
              //y : {xs:float},
              //space : {xs:anyURI}
            //}
          //},
          //Zoom : { 
            //attributes : {
              //x : {xs:float},
              //space : {xs:anyURI}
            //}
          //}
        //},
        //Speed : { 
          //PanTilt : { 
            //attributes : {
              //x : {xs:float},
              //y : {xs:float},
              //space : {xs:anyURI}
            //}
          //},
          //Zoom : { 
            //attributes : {
              //x : {xs:float},
              //space : {xs:anyURI}
            //}
          //}
        //}
      //
      //};
      AbsoluteMove : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var AbsoluteMoveResponse = { };
        //return AbsoluteMoveResponse;
      },

      //var Stop = { 
        //ProfileToken : { xs:string},
        //PanTilt : { xs:boolean},
        //Zoom : { xs:boolean}
      //
      //};
      Stop : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var StopResponse = { };
        //return StopResponse;
      },

      //var GetPresetTours = { 
        //ProfileToken : { xs:string}
      //
      //};
      GetPresetTours : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetPresetToursResponse = { 
          //PresetTour : [{ 
            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //Status : { 
              //State : { xs:string},
              //CurrentTourSpot : { 
                //PresetDetail : { },
                //Speed : { 
                  //PanTilt : { 
                    //attributes : {
                      //x : {xs:float},
                      //y : {xs:float},
                      //space : {xs:anyURI}
                    //}
                  //},
                  //Zoom : { 
                    //attributes : {
                      //x : {xs:float},
                      //space : {xs:anyURI}
                    //}
                  //}
                //},
                //StayTime : { xs:duration},
                //Extension : { }
              //},
              //Extension : { }
            //},
            //AutoStart : { xs:boolean},
            //StartingCondition : { 
              //attributes : {
                //RandomPresetOrder : {xs:boolean}
              //},
              //RecurringTime : { xs:int},
              //RecurringDuration : { xs:duration},
              //Direction : { xs:string},
              //Extension : { }
            //},
            //TourSpot : [{ 
              //PresetDetail : { },
              //Speed : { 
                //PanTilt : { 
                  //attributes : {
                    //x : {xs:float},
                    //y : {xs:float},
                    //space : {xs:anyURI}
                  //}
                //},
                //Zoom : { 
                  //attributes : {
                    //x : {xs:float},
                    //space : {xs:anyURI}
                  //}
                //}
              //},
              //StayTime : { xs:duration},
              //Extension : { }
            //}],
            //Extension : { }
          //}]
        //
        //};
        //return GetPresetToursResponse;
      },

      //var GetPresetTour = { 
        //ProfileToken : { xs:string},
        //PresetTourToken : { xs:string}
      //
      //};
      GetPresetTour : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetPresetTourResponse = { 
          //PresetTour : { 
            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //Status : { 
              //State : { xs:string},
              //CurrentTourSpot : { 
                //PresetDetail : { },
                //Speed : { 
                  //PanTilt : { 
                    //attributes : {
                      //x : {xs:float},
                      //y : {xs:float},
                      //space : {xs:anyURI}
                    //}
                  //},
                  //Zoom : { 
                    //attributes : {
                      //x : {xs:float},
                      //space : {xs:anyURI}
                    //}
                  //}
                //},
                //StayTime : { xs:duration},
                //Extension : { }
              //},
              //Extension : { }
            //},
            //AutoStart : { xs:boolean},
            //StartingCondition : { 
              //attributes : {
                //RandomPresetOrder : {xs:boolean}
              //},
              //RecurringTime : { xs:int},
              //RecurringDuration : { xs:duration},
              //Direction : { xs:string},
              //Extension : { }
            //},
            //TourSpot : [{ 
              //PresetDetail : { },
              //Speed : { 
                //PanTilt : { 
                  //attributes : {
                    //x : {xs:float},
                    //y : {xs:float},
                    //space : {xs:anyURI}
                  //}
                //},
                //Zoom : { 
                  //attributes : {
                    //x : {xs:float},
                    //space : {xs:anyURI}
                  //}
                //}
              //},
              //StayTime : { xs:duration},
              //Extension : { }
            //}],
            //Extension : { }
          //}
        //
        //};
        //return GetPresetTourResponse;
      },

      //var GetPresetTourOptions = { 
        //ProfileToken : { xs:string},
        //PresetTourToken : { xs:string}
      //
      //};
      GetPresetTourOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetPresetTourOptionsResponse = { 
          //Options : { 
            //AutoStart : { xs:boolean},
            //StartingCondition : { 
              //RecurringTime : { 
                //Min : { xs:int},
                //Max : { xs:int}
              //},
              //RecurringDuration : { 
                //Min : { xs:duration},
                //Max : { xs:duration}
              //},
              //Direction : [{ xs:string}],
              //Extension : { }
            //},
            //TourSpot : { 
              //PresetDetail : { 
                //PresetToken : [{ xs:string}],
                //Home : { xs:boolean},
                //PanTiltPositionSpace : { 
                  //URI : { xs:anyURI},
                  //XRange : { 
                    //Min : { xs:float},
                    //Max : { xs:float}
                  //},
                  //YRange : { 
                    //Min : { xs:float},
                    //Max : { xs:float}
                  //}
                //},
                //ZoomPositionSpace : { 
                  //URI : { xs:anyURI},
                  //XRange : { 
                    //Min : { xs:float},
                    //Max : { xs:float}
                  //}
                //},
                //Extension : { }
              //},
              //StayTime : { 
                //Min : { xs:duration},
                //Max : { xs:duration}
              //}
            //}
          //}
        //
        //};
        //return GetPresetTourOptionsResponse;
      },

      //var CreatePresetTour = { 
        //ProfileToken : { xs:string}
      //
      //};
      CreatePresetTour : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var CreatePresetTourResponse = { 
          //PresetTourToken : { xs:string}
        //
        //};
        //return CreatePresetTourResponse;
      },

      //var ModifyPresetTour = { 
        //ProfileToken : { xs:string},
        //PresetTour : { 
          //attributes : {
            //token : {tt:ReferenceToken}
          //},
          //Name : { xs:string},
          //Status : { 
            //State : { xs:string},
            //CurrentTourSpot : { 
              //PresetDetail : { },
              //Speed : { 
                //PanTilt : { 
                  //attributes : {
                    //x : {xs:float},
                    //y : {xs:float},
                    //space : {xs:anyURI}
                  //}
                //},
                //Zoom : { 
                  //attributes : {
                    //x : {xs:float},
                    //space : {xs:anyURI}
                  //}
                //}
              //},
              //StayTime : { xs:duration},
              //Extension : { }
            //},
            //Extension : { }
          //},
          //AutoStart : { xs:boolean},
          //StartingCondition : { 
            //attributes : {
              //RandomPresetOrder : {xs:boolean}
            //},
            //RecurringTime : { xs:int},
            //RecurringDuration : { xs:duration},
            //Direction : { xs:string},
            //Extension : { }
          //},
          //TourSpot : [{ 
            //PresetDetail : { },
            //Speed : { 
              //PanTilt : { 
                //attributes : {
                  //x : {xs:float},
                  //y : {xs:float},
                  //space : {xs:anyURI}
                //}
              //},
              //Zoom : { 
                //attributes : {
                  //x : {xs:float},
                  //space : {xs:anyURI}
                //}
              //}
            //},
            //StayTime : { xs:duration},
            //Extension : { }
          //}],
          //Extension : { }
        //}
      //
      //};
      ModifyPresetTour : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var ModifyPresetTourResponse = { };
        //return ModifyPresetTourResponse;
      },

      //var OperatePresetTour = { 
        //ProfileToken : { xs:string},
        //PresetTourToken : { xs:string},
        //Operation : { xs:string}
      //
      //};
      OperatePresetTour : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var OperatePresetTourResponse = { };
        //return OperatePresetTourResponse;
      },

      //var RemovePresetTour = { 
        //ProfileToken : { xs:string},
        //PresetTourToken : { xs:string}
      //
      //};
      RemovePresetTour : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var RemovePresetTourResponse = { };
        //return RemovePresetTourResponse;
      },

      //var GetCompatibleConfigurations = { 
        //ProfileToken : { xs:string}
      //
      //};
      GetCompatibleConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetCompatibleConfigurationsResponse = { 
          //PTZConfiguration : [{ 
            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
            //attributes : {
              //MoveRamp : {xs:int},
              //PresetRamp : {xs:int},
              //PresetTourRamp : {xs:int}
            //},
            //NodeToken : { xs:string},
            //DefaultAbsolutePantTiltPositionSpace : { xs:anyURI},
            //DefaultAbsoluteZoomPositionSpace : { xs:anyURI},
            //DefaultRelativePanTiltTranslationSpace : { xs:anyURI},
            //DefaultRelativeZoomTranslationSpace : { xs:anyURI},
            //DefaultContinuousPanTiltVelocitySpace : { xs:anyURI},
            //DefaultContinuousZoomVelocitySpace : { xs:anyURI},
            //DefaultPTZSpeed : { 
              //PanTilt : { 
                //attributes : {
                  //x : {xs:float},
                  //y : {xs:float},
                  //space : {xs:anyURI}
                //}
              //},
              //Zoom : { 
                //attributes : {
                  //x : {xs:float},
                  //space : {xs:anyURI}
                //}
              //}
            //},
            //DefaultPTZTimeout : { xs:duration},
            //PanTiltLimits : { 
              //Range : { 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //},
                //YRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}
            //},
            //ZoomLimits : { 
              //Range : { 
                //URI : { xs:anyURI},
                //XRange : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //}
              //}
            //},
            //Extension : { 
              //PTControlDirection : { 
                //EFlip : { 
                  //Mode : { xs:string}
                //},
                //Reverse : { 
                  //Mode : { xs:string}
                //},
                //Extension : { }
              //},
              //Extension : { }
            //}
          //}]
        //
        //};
        //return GetCompatibleConfigurationsResponse;
      },

    }
  }
}
