<?xml version="1.0" encoding="utf-8" ?>
<wsdl:definitions xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:i0="http://www.onvif.org/ver10/device/wsdl" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://tempuri.org/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://tempuri.org/">
  <wsdl:import namespace="http://www.onvif.org/ver10/media/wsdl" location="./www.onvif.org.ver10.media.wsdl"/>
  <wsdl:types>
    <s:schema targetNamespace="http://versteege.com/rpos">
      <s:import schemaLocation="./www.onvif.org.ver10.media.wsdl" namespace="http://www.onvif.org/ver10/media/wsdl"/>
    </s:schema>
  </wsdl:types>
  <wsdl:service name="MediaService">
    <wsdl:port name="Media" binding="i0:MediaBinding">
      <soap:address location="http://localhost:8000/onvif/media_service" />
      <soap:address location="http://localhost:8000/" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>