// This file is generated by the 'node-soap-servicegenerator'
// visit : https://github.com/BreeeZe/node-soap-servicegenerator for more info

var NOT_IMPLEMENTED = {
  Fault: {
    Code: {
      Value: "soap:client"
    },
    Reason: {
      Text: "Method not implemented"
    }
  }
};
var exports = module.exports = {};

exports.ImagingService = {
  ImagingService : {
    Imaging : {
      //var GetServiceCapabilities = { };
      GetServiceCapabilities : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetServiceCapabilitiesResponse = { 
          //Capabilities : { 
            //attributes : {
              //ImageStabilization : {xs:boolean},
              //Presets : {xs:boolean}
            //}
          //}
        //
        //};
        //return GetServiceCapabilitiesResponse;
      },

      //var GetImagingSettings = { 
        //VideoSourceToken : { xs:string}
      //
      //};
      GetImagingSettings : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetImagingSettingsResponse = { 
          //ImagingSettings : { 
            //BacklightCompensation : { 
              //Mode : { xs:string},
              //Level : { xs:float}
            //},
            //Brightness : { xs:float},
            //ColorSaturation : { xs:float},
            //Contrast : { xs:float},
            //Exposure : { 
              //Mode : { xs:string},
              //Priority : { xs:string},
              //Window : { 
                //attributes : {
                  //bottom : {xs:float},
                  //top : {xs:float},
                  //right : {xs:float},
                  //left : {xs:float}
                //}
              //},
              //MinExposureTime : { xs:float},
              //MaxExposureTime : { xs:float},
              //MinGain : { xs:float},
              //MaxGain : { xs:float},
              //MinIris : { xs:float},
              //MaxIris : { xs:float},
              //ExposureTime : { xs:float},
              //Gain : { xs:float},
              //Iris : { xs:float}
            //},
            //Focus : { 
              //AutoFocusMode : { xs:string},
              //DefaultSpeed : { xs:float},
              //NearLimit : { xs:float},
              //FarLimit : { xs:float},
              //Extension : { }
            //},
            //IrCutFilter : { xs:string},
            //Sharpness : { xs:float},
            //WideDynamicRange : { 
              //Mode : { xs:string},
              //Level : { xs:float}
            //},
            //WhiteBalance : { 
              //Mode : { xs:string},
              //CrGain : { xs:float},
              //CbGain : { xs:float},
              //Extension : { }
            //},
            //Extension : { 
              //ImageStabilization : { 
                //Mode : { xs:string},
                //Level : { xs:float},
                //Extension : { }
              //},
              //Extension : { 
                //IrCutFilterAutoAdjustment : [{ 
                  //BoundaryType : { xs:string},
                  //BoundaryOffset : { xs:float},
                  //ResponseTime : { xs:duration},
                  //Extension : { }
                //}],
                //Extension : { 
                  //ToneCompensation : { 
                    //Mode : { xs:string},
                    //Level : { xs:float},
                    //Extension : { }
                  //},
                  //Defogging : { 
                    //Mode : { xs:string},
                    //Level : { xs:float},
                    //Extension : { }
                  //},
                  //NoiseReduction : { 
                    //Level : { xs:float}
                  //},
                  //Extension : { }
                //}
              //}
            //}
          //}
        //
        //};
        //return GetImagingSettingsResponse;
      },

      //var SetImagingSettings = { 
        //VideoSourceToken : { xs:string},
        //ImagingSettings : { 
          //BacklightCompensation : { 
            //Mode : { xs:string},
            //Level : { xs:float}
          //},
          //Brightness : { xs:float},
          //ColorSaturation : { xs:float},
          //Contrast : { xs:float},
          //Exposure : { 
            //Mode : { xs:string},
            //Priority : { xs:string},
            //Window : { 
              //attributes : {
                //bottom : {xs:float},
                //top : {xs:float},
                //right : {xs:float},
                //left : {xs:float}
              //}
            //},
            //MinExposureTime : { xs:float},
            //MaxExposureTime : { xs:float},
            //MinGain : { xs:float},
            //MaxGain : { xs:float},
            //MinIris : { xs:float},
            //MaxIris : { xs:float},
            //ExposureTime : { xs:float},
            //Gain : { xs:float},
            //Iris : { xs:float}
          //},
          //Focus : { 
            //AutoFocusMode : { xs:string},
            //DefaultSpeed : { xs:float},
            //NearLimit : { xs:float},
            //FarLimit : { xs:float},
            //Extension : { }
          //},
          //IrCutFilter : { xs:string},
          //Sharpness : { xs:float},
          //WideDynamicRange : { 
            //Mode : { xs:string},
            //Level : { xs:float}
          //},
          //WhiteBalance : { 
            //Mode : { xs:string},
            //CrGain : { xs:float},
            //CbGain : { xs:float},
            //Extension : { }
          //},
          //Extension : { 
            //ImageStabilization : { 
              //Mode : { xs:string},
              //Level : { xs:float},
              //Extension : { }
            //},
            //Extension : { 
              //IrCutFilterAutoAdjustment : [{ 
                //BoundaryType : { xs:string},
                //BoundaryOffset : { xs:float},
                //ResponseTime : { xs:duration},
                //Extension : { }
              //}],
              //Extension : { 
                //ToneCompensation : { 
                  //Mode : { xs:string},
                  //Level : { xs:float},
                  //Extension : { }
                //},
                //Defogging : { 
                  //Mode : { xs:string},
                  //Level : { xs:float},
                  //Extension : { }
                //},
                //NoiseReduction : { 
                  //Level : { xs:float}
                //},
                //Extension : { }
              //}
            //}
          //}
        //},
        //ForcePersistence : [{ xs:boolean}]
      //
      //};
      SetImagingSettings : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetImagingSettingsResponse = { };
        //return SetImagingSettingsResponse;
      },

      //var GetOptions = { 
        //VideoSourceToken : { xs:string}
      //
      //};
      GetOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetOptionsResponse = { 
          //ImagingOptions : { 
            //BacklightCompensation : { 
              //Mode : { xs:string},
              //Level : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //}
            //},
            //Brightness : { 
              //Min : { xs:float},
              //Max : { xs:float}
            //},
            //ColorSaturation : { 
              //Min : { xs:float},
              //Max : { xs:float}
            //},
            //Contrast : { 
              //Min : { xs:float},
              //Max : { xs:float}
            //},
            //Exposure : { 
              //Mode : { xs:string},
              //Priority : [{ xs:string}],
              //MinExposureTime : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //},
              //MaxExposureTime : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //},
              //MinGain : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //},
              //MaxGain : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //},
              //MinIris : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //},
              //MaxIris : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //},
              //ExposureTime : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //},
              //Gain : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //},
              //Iris : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //}
            //},
            //Focus : { 
              //AutoFocusModes : [{ xs:string}],
              //DefaultSpeed : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //},
              //NearLimit : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //},
              //FarLimit : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //},
              //Extension : { }
            //},
            //IrCutFilterModes : [{ xs:string}],
            //Sharpness : { 
              //Min : { xs:float},
              //Max : { xs:float}
            //},
            //WideDynamicRange : { 
              //Mode : { xs:string},
              //Level : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //}
            //},
            //WhiteBalance : { 
              //Mode : { xs:string},
              //YrGain : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //},
              //YbGain : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //},
              //Extension : { }
            //},
            //Extension : { 
              //ImageStabilization : { 
                //Mode : { xs:string},
                //Level : { 
                  //Min : { xs:float},
                  //Max : { xs:float}
                //},
                //Extension : { }
              //},
              //Extension : { 
                //IrCutFilterAutoAdjustment : { 
                  //BoundaryType : { xs:string},
                  //BoundaryOffset : { xs:boolean},
                  //ResponseTimeRange : { 
                    //Min : { xs:duration},
                    //Max : { xs:duration}
                  //},
                  //Extension : { }
                //},
                //Extension : { 
                  //ToneCompensationOptions : { 
                    //Mode : { xs:string},
                    //Level : { xs:boolean}
                  //},
                  //DefoggingOptions : { 
                    //Mode : { xs:string},
                    //Level : { xs:boolean}
                  //},
                  //NoiseReductionOptions : { 
                    //Level : { xs:boolean}
                  //},
                  //Extension : { }
                //}
              //}
            //}
          //}
        //
        //};
        //return GetOptionsResponse;
      },

      //var Move = { 
        //VideoSourceToken : { xs:string},
        //Focus : { 
          //Absolute : { 
            //Position : { xs:float},
            //Speed : { xs:float}
          //},
          //Relative : { 
            //Distance : { xs:float},
            //Speed : { xs:float}
          //},
          //Continuous : { 
            //Speed : { xs:float}
          //}
        //}
      //
      //};
      Move : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var MoveResponse = { };
        //return MoveResponse;
      },

      //var GetMoveOptions = { 
        //VideoSourceToken : { xs:string}
      //
      //};
      GetMoveOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetMoveOptionsResponse = { 
          //MoveOptions : { 
            //Absolute : { 
              //Position : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //},
              //Speed : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //}
            //},
            //Relative : { 
              //Distance : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //},
              //Speed : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //}
            //},
            //Continuous : { 
              //Speed : { 
                //Min : { xs:float},
                //Max : { xs:float}
              //}
            //}
          //}
        //
        //};
        //return GetMoveOptionsResponse;
      },

      //var Stop = { 
        //VideoSourceToken : { xs:string}
      //
      //};
      Stop : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var StopResponse = { };
        //return StopResponse;
      },

      //var GetStatus = { 
        //VideoSourceToken : { xs:string}
      //
      //};
      GetStatus : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetStatusResponse = { 
          //Status : { 
            //FocusStatus20 : { 
              //Position : { xs:float},
              //MoveStatus : { xs:string},
              //Error : { xs:string},
              //Extension : { }
            //},
            //Extension : { }
          //}
        //
        //};
        //return GetStatusResponse;
      },

      //var GetPresets = { 
        //VideoSourceToken : { xs:string}
      //
      //};
      GetPresets : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetPresetsResponse = { 
          //Preset : { 
            //attributes : {
              //token : {tt:ReferenceToken},
              //type : {xs:string}
            //},
            //Name : { xs:string}
          //}
        //
        //};
        //return GetPresetsResponse;
      },

      //var GetCurrentPreset = { 
        //VideoSourceToken : { xs:string}
      //
      //};
      GetCurrentPreset : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetCurrentPresetResponse = { 
          //Preset : { 
            //attributes : {
              //token : {tt:ReferenceToken},
              //type : {xs:string}
            //},
            //Name : { xs:string}
          //}
        //
        //};
        //return GetCurrentPresetResponse;
      },

      //var SetCurrentPreset = { 
        //VideoSourceToken : { xs:string},
        //PresetToken : { xs:string}
      //
      //};
      SetCurrentPreset : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetCurrentPresetResponse = { };
        //return SetCurrentPresetResponse;
      },

    }
  }
}
