// This file is generated by the 'node-soap-servicegenerator'
// visit : https://github.com/BreeeZe/node-soap-servicegenerator for more info

var NOT_IMPLEMENTED = {
  Fault: {
    Code: {
      Value: "soap:client"
    },
    Reason: {
      Text: "Method not implemented"
    }
  }
};
var exports = module.exports = {};

exports.Media2Service = {
  Media2Service : {
    Media2 : {
      //var GetServiceCapabilities = { };
      GetServiceCapabilities : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetServiceCapabilitiesResponse = { 
          //Capabilities : { 
            //attributes : {
              //SnapshotUri : {xs:boolean},
              //Rotation : {xs:boolean},
              //VideoSourceMode : {xs:boolean},
              //OSD : {xs:boolean},
              //TemporaryOSDText : {xs:boolean},
              //Mask : {xs:boolean},
              //SourceMask : {xs:boolean}
            //},
            //ProfileCapabilities : { 
              //attributes : {
                //MaximumNumberOfProfiles : {xs:int},
                //ConfigurationsSupported : {tt:StringAttrList}
              //}
            //},
            //StreamingCapabilities : { 
              //attributes : {
                //RTSPStreaming : {xs:boolean},
                //RTPMulticast : {xs:boolean},
                //RTP_RTSP_TCP : {xs:boolean},
                //NonAggregateControl : {xs:boolean},
                //RTSPWebSocketUri : {xs:anyURI},
                //AutoStartMulticast : {xs:boolean}
              //}
            //}
          //}
        //
        //};
        //return GetServiceCapabilitiesResponse;
      },

      //var CreateProfile = { 
        //Name : { xs:string},
        //Configuration : [{ 
          //Type : { xs:string},
          //Token : { xs:string}
        //}]
      //
      //};
      CreateProfile : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var CreateProfileResponse = { 
          //Token : { xs:string}
        //
        //};
        //return CreateProfileResponse;
      },

      //var GetProfiles = { 
        //Token : { xs:string},
        //Type : [{ xs:string}]
      //
      //};
      GetProfiles : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetProfilesResponse = { 
          //Profiles : [{ 
            //attributes : {
              //token : {tt:ReferenceToken},
              //fixed : {xs:boolean}
            //},
            //Name : { xs:string},
            //Configurations : { 
              //VideoSource : { 
                //attributes : {
                  //token : {tt:ReferenceToken}
                //},
                //Name : { xs:string},
                //UseCount : { xs:int}
              //
                //SourceToken : { xs:string},
                //Bounds : { 
                  //attributes : {
                    //x : {xs:int},
                    //y : {xs:int},
                    //width : {xs:int},
                    //height : {xs:int}
                  //}
                //},
                //Extension : { 
                  //Rotate : { 
                    //Mode : { xs:string},
                    //Degree : { xs:int},
                    //Extension : { }
                  //},
                  //Extension : { }
                //}
              //},
              //AudioSource : { 
                //attributes : {
                  //token : {tt:ReferenceToken}
                //},
                //Name : { xs:string},
                //UseCount : { xs:int}
              //
                //SourceToken : { xs:string}
              //},
              //VideoEncoder : { tt:VideoEncoder2Configuration},
              //AudioEncoder : { tt:AudioEncoder2Configuration},
              //Analytics : { 
                //attributes : {
                  //token : {tt:ReferenceToken}
                //},
                //Name : { xs:string},
                //UseCount : { xs:int}
              //
                //AnalyticsEngineConfiguration : { 
                  //AnalyticsModule : [{ 
                    //attributes : {
                      //Name : {xs:string},
                      //Type : {xs:QName}
                    //},
                    //Parameters : { 
                      //SimpleItem : [{ }],
                      //ElementItem : [{ }],
                      //Extension : { }
                    //}
                  //}],
                  //Extension : { }
                //},
                //RuleEngineConfiguration : { 
                  //Rule : [{ 
                    //attributes : {
                      //Name : {xs:string},
                      //Type : {xs:QName}
                    //},
                    //Parameters : { 
                      //SimpleItem : [{ }],
                      //ElementItem : [{ }],
                      //Extension : { }
                    //}
                  //}],
                  //Extension : { }
                //}
              //},
              //PTZ : { 
                //attributes : {
                  //token : {tt:ReferenceToken}
                //},
                //Name : { xs:string},
                //UseCount : { xs:int}
              //
                //attributes : {
                  //MoveRamp : {xs:int},
                  //PresetRamp : {xs:int},
                  //PresetTourRamp : {xs:int}
                //},
                //NodeToken : { xs:string},
                //DefaultAbsolutePantTiltPositionSpace : { xs:anyURI},
                //DefaultAbsoluteZoomPositionSpace : { xs:anyURI},
                //DefaultRelativePanTiltTranslationSpace : { xs:anyURI},
                //DefaultRelativeZoomTranslationSpace : { xs:anyURI},
                //DefaultContinuousPanTiltVelocitySpace : { xs:anyURI},
                //DefaultContinuousZoomVelocitySpace : { xs:anyURI},
                //DefaultPTZSpeed : { 
                  //PanTilt : { 
                    //attributes : {
                      //x : {xs:float},
                      //y : {xs:float},
                      //space : {xs:anyURI}
                    //}
                  //},
                  //Zoom : { 
                    //attributes : {
                      //x : {xs:float},
                      //space : {xs:anyURI}
                    //}
                  //}
                //},
                //DefaultPTZTimeout : { xs:duration},
                //PanTiltLimits : { 
                  //Range : { 
                    //URI : { xs:anyURI},
                    //XRange : { 
                      //Min : { xs:float},
                      //Max : { xs:float}
                    //},
                    //YRange : { 
                      //Min : { xs:float},
                      //Max : { xs:float}
                    //}
                  //}
                //},
                //ZoomLimits : { 
                  //Range : { 
                    //URI : { xs:anyURI},
                    //XRange : { 
                      //Min : { xs:float},
                      //Max : { xs:float}
                    //}
                  //}
                //},
                //Extension : { 
                  //PTControlDirection : { 
                    //EFlip : { 
                      //Mode : { xs:string}
                    //},
                    //Reverse : { 
                      //Mode : { xs:string}
                    //},
                    //Extension : { }
                  //},
                  //Extension : { }
                //}
              //},
              //Metadata : { 
                //attributes : {
                  //token : {tt:ReferenceToken}
                //},
                //Name : { xs:string},
                //UseCount : { xs:int}
              //
                //attributes : {
                  //CompressionType : {xs:string}
                //},
                //PTZStatus : { 
                  //Status : { xs:boolean},
                  //Position : { xs:boolean}
                //},
                //Events : { 
                  //Filter : { wsnt:FilterType},
                  //SubscriptionPolicy : { }
                //},
                //Analytics : { xs:boolean},
                //Multicast : { 
                  //Address : { 
                    //Type : { xs:string},
                    //IPv4Address : { xs:token},
                    //IPv6Address : { xs:token}
                  //},
                  //Port : { xs:int},
                  //TTL : { xs:int},
                  //AutoStart : { xs:boolean}
                //},
                //SessionTimeout : { xs:duration},
                //AnalyticsEngineConfiguration : { 
                  //AnalyticsModule : [{ 
                    //attributes : {
                      //Name : {xs:string},
                      //Type : {xs:QName}
                    //},
                    //Parameters : { 
                      //SimpleItem : [{ }],
                      //ElementItem : [{ }],
                      //Extension : { }
                    //}
                  //}],
                  //Extension : { }
                //},
                //Extension : { }
              //},
              //AudioOutput : { 
                //attributes : {
                  //token : {tt:ReferenceToken}
                //},
                //Name : { xs:string},
                //UseCount : { xs:int}
              //
                //OutputToken : { xs:string},
                //SendPrimacy : { xs:anyURI},
                //OutputLevel : { xs:int}
              //},
              //AudioDecoder : { 
                //attributes : {
                  //token : {tt:ReferenceToken}
                //},
                //Name : { xs:string},
                //UseCount : { xs:int}
              //}
            //}
          //}]
        //
        //};
        //return GetProfilesResponse;
      },

      //var AddConfiguration = { 
        //ProfileToken : { xs:string},
        //Name : { xs:string},
        //Configuration : [{ 
          //Type : { xs:string},
          //Token : { xs:string}
        //}]
      //
      //};
      AddConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var AddConfigurationResponse = { };
        //return AddConfigurationResponse;
      },

      //var RemoveConfiguration = { 
        //ProfileToken : { xs:string},
        //Configuration : { 
          //Type : { xs:string},
          //Token : { xs:string}
        //}
      //
      //};
      RemoveConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var RemoveConfigurationResponse = { };
        //return RemoveConfigurationResponse;
      },

      //var DeleteProfile = { 
        //Token : { xs:string}
      //
      //};
      DeleteProfile : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var DeleteProfileResponse = { };
        //return DeleteProfileResponse;
      },

      //var GetVideoSourceConfigurations = { };
      GetVideoSourceConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetVideoSourceConfigurationsResponse = { 
          //Configurations : [{ 
            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
            //SourceToken : { xs:string},
            //Bounds : { 
              //attributes : {
                //x : {xs:int},
                //y : {xs:int},
                //width : {xs:int},
                //height : {xs:int}
              //}
            //},
            //Extension : { 
              //Rotate : { 
                //Mode : { xs:string},
                //Degree : { xs:int},
                //Extension : { }
              //},
              //Extension : { }
            //}
          //}]
        //
        //};
        //return GetVideoSourceConfigurationsResponse;
      },

      //var GetVideoEncoderConfigurations = { };
      GetVideoEncoderConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetVideoEncoderConfigurationsResponse = { 
          //Configurations : [{ tt:VideoEncoder2Configuration}]
        //
        //};
        //return GetVideoEncoderConfigurationsResponse;
      },

      //var GetAudioSourceConfigurations = { };
      GetAudioSourceConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioSourceConfigurationsResponse = { 
          //Configurations : [{ 
            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
            //SourceToken : { xs:string}
          //}]
        //
        //};
        //return GetAudioSourceConfigurationsResponse;
      },

      //var GetAudioEncoderConfigurations = { };
      GetAudioEncoderConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioEncoderConfigurationsResponse = { 
          //Configurations : [{ tt:AudioEncoder2Configuration}]
        //
        //};
        //return GetAudioEncoderConfigurationsResponse;
      },

      //var GetAnalyticsConfigurations = { };
      GetAnalyticsConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAnalyticsConfigurationsResponse = { 
          //Configurations : [{ 
            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
            //AnalyticsEngineConfiguration : { 
              //AnalyticsModule : [{ 
                //attributes : {
                  //Name : {xs:string},
                  //Type : {xs:QName}
                //},
                //Parameters : { 
                  //SimpleItem : [{ }],
                  //ElementItem : [{ }],
                  //Extension : { }
                //}
              //}],
              //Extension : { }
            //},
            //RuleEngineConfiguration : { 
              //Rule : [{ 
                //attributes : {
                  //Name : {xs:string},
                  //Type : {xs:QName}
                //},
                //Parameters : { 
                  //SimpleItem : [{ }],
                  //ElementItem : [{ }],
                  //Extension : { }
                //}
              //}],
              //Extension : { }
            //}
          //}]
        //
        //};
        //return GetAnalyticsConfigurationsResponse;
      },

      //var GetMetadataConfigurations = { };
      GetMetadataConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetMetadataConfigurationsResponse = { 
          //Configurations : [{ 
            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
            //attributes : {
              //CompressionType : {xs:string}
            //},
            //PTZStatus : { 
              //Status : { xs:boolean},
              //Position : { xs:boolean}
            //},
            //Events : { 
              //Filter : { wsnt:FilterType},
              //SubscriptionPolicy : { }
            //},
            //Analytics : { xs:boolean},
            //Multicast : { 
              //Address : { 
                //Type : { xs:string},
                //IPv4Address : { xs:token},
                //IPv6Address : { xs:token}
              //},
              //Port : { xs:int},
              //TTL : { xs:int},
              //AutoStart : { xs:boolean}
            //},
            //SessionTimeout : { xs:duration},
            //AnalyticsEngineConfiguration : { 
              //AnalyticsModule : [{ 
                //attributes : {
                  //Name : {xs:string},
                  //Type : {xs:QName}
                //},
                //Parameters : { 
                  //SimpleItem : [{ }],
                  //ElementItem : [{ }],
                  //Extension : { }
                //}
              //}],
              //Extension : { }
            //},
            //Extension : { }
          //}]
        //
        //};
        //return GetMetadataConfigurationsResponse;
      },

      //var GetAudioOutputConfigurations = { };
      GetAudioOutputConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioOutputConfigurationsResponse = { 
          //Configurations : [{ 
            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
            //OutputToken : { xs:string},
            //SendPrimacy : { xs:anyURI},
            //OutputLevel : { xs:int}
          //}]
        //
        //};
        //return GetAudioOutputConfigurationsResponse;
      },

      //var GetAudioDecoderConfigurations = { };
      GetAudioDecoderConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioDecoderConfigurationsResponse = { 
          //Configurations : [{ 
            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //}]
        //
        //};
        //return GetAudioDecoderConfigurationsResponse;
      },

      //var SetVideoSourceConfiguration = { 
        //Configuration : { 
          //attributes : {
            //token : {tt:ReferenceToken}
          //},
          //Name : { xs:string},
          //UseCount : { xs:int}
        //
          //SourceToken : { xs:string},
          //Bounds : { 
            //attributes : {
              //x : {xs:int},
              //y : {xs:int},
              //width : {xs:int},
              //height : {xs:int}
            //}
          //},
          //Extension : { 
            //Rotate : { 
              //Mode : { xs:string},
              //Degree : { xs:int},
              //Extension : { }
            //},
            //Extension : { }
          //}
        //}
      //
      //};
      SetVideoSourceConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetVideoSourceConfigurationResponse = { };
        //return SetVideoSourceConfigurationResponse;
      },

      //var SetVideoEncoderConfiguration = { 
        //Configuration : { tt:VideoEncoder2Configuration}
      //
      //};
      SetVideoEncoderConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetVideoEncoderConfigurationResponse = { };
        //return SetVideoEncoderConfigurationResponse;
      },

      //var SetAudioSourceConfiguration = { 
        //Configuration : { 
          //attributes : {
            //token : {tt:ReferenceToken}
          //},
          //Name : { xs:string},
          //UseCount : { xs:int}
        //
          //SourceToken : { xs:string}
        //}
      //
      //};
      SetAudioSourceConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetAudioSourceConfigurationResponse = { };
        //return SetAudioSourceConfigurationResponse;
      },

      //var SetAudioEncoderConfiguration = { 
        //Configuration : { tt:AudioEncoder2Configuration}
      //
      //};
      SetAudioEncoderConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetAudioEncoderConfigurationResponse = { };
        //return SetAudioEncoderConfigurationResponse;
      },

      //var SetMetadataConfiguration = { 
        //Configuration : { 
          //attributes : {
            //token : {tt:ReferenceToken}
          //},
          //Name : { xs:string},
          //UseCount : { xs:int}
        //
          //attributes : {
            //CompressionType : {xs:string}
          //},
          //PTZStatus : { 
            //Status : { xs:boolean},
            //Position : { xs:boolean}
          //},
          //Events : { 
            //Filter : { wsnt:FilterType},
            //SubscriptionPolicy : { }
          //},
          //Analytics : { xs:boolean},
          //Multicast : { 
            //Address : { 
              //Type : { xs:string},
              //IPv4Address : { xs:token},
              //IPv6Address : { xs:token}
            //},
            //Port : { xs:int},
            //TTL : { xs:int},
            //AutoStart : { xs:boolean}
          //},
          //SessionTimeout : { xs:duration},
          //AnalyticsEngineConfiguration : { 
            //AnalyticsModule : [{ 
              //attributes : {
                //Name : {xs:string},
                //Type : {xs:QName}
              //},
              //Parameters : { 
                //SimpleItem : [{ }],
                //ElementItem : [{ }],
                //Extension : { }
              //}
            //}],
            //Extension : { }
          //},
          //Extension : { }
        //}
      //
      //};
      SetMetadataConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetMetadataConfigurationResponse = { };
        //return SetMetadataConfigurationResponse;
      },

      //var SetAudioOutputConfiguration = { 
        //Configuration : { 
          //attributes : {
            //token : {tt:ReferenceToken}
          //},
          //Name : { xs:string},
          //UseCount : { xs:int}
        //
          //OutputToken : { xs:string},
          //SendPrimacy : { xs:anyURI},
          //OutputLevel : { xs:int}
        //}
      //
      //};
      SetAudioOutputConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetAudioOutputConfigurationResponse = { };
        //return SetAudioOutputConfigurationResponse;
      },

      //var SetAudioDecoderConfiguration = { 
        //Configuration : { 
          //attributes : {
            //token : {tt:ReferenceToken}
          //},
          //Name : { xs:string},
          //UseCount : { xs:int}
        //}
      //
      //};
      SetAudioDecoderConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetAudioDecoderConfigurationResponse = { };
        //return SetAudioDecoderConfigurationResponse;
      },

      //var GetVideoSourceConfigurationOptions = { };
      GetVideoSourceConfigurationOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetVideoSourceConfigurationOptionsResponse = { 
          //Options : { 
            //BoundsRange : { 
              //XRange : { 
                //Min : { xs:int},
                //Max : { xs:int}
              //},
              //YRange : { 
                //Min : { xs:int},
                //Max : { xs:int}
              //},
              //WidthRange : { 
                //Min : { xs:int},
                //Max : { xs:int}
              //},
              //HeightRange : { 
                //Min : { xs:int},
                //Max : { xs:int}
              //}
            //},
            //VideoSourceTokensAvailable : { xs:string},
            //Extension : { 
              //Rotate : { 
                //Mode : { xs:string},
                //DegreeList : { 
                  //Items : [{ xs:int}]
                //},
                //Extension : { }
              //},
              //Extension : { }
            //}
          //}
        //
        //};
        //return GetVideoSourceConfigurationOptionsResponse;
      },

      //var GetVideoEncoderConfigurationOptions = { };
      GetVideoEncoderConfigurationOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetVideoEncoderConfigurationOptionsResponse = { 
          //Options : { tt:VideoEncoder2ConfigurationOptions}
        //
        //};
        //return GetVideoEncoderConfigurationOptionsResponse;
      },

      //var GetAudioSourceConfigurationOptions = { };
      GetAudioSourceConfigurationOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioSourceConfigurationOptionsResponse = { 
          //Options : { 
            //InputTokensAvailable : { xs:string},
            //Extension : { }
          //}
        //
        //};
        //return GetAudioSourceConfigurationOptionsResponse;
      },

      //var GetAudioEncoderConfigurationOptions = { };
      GetAudioEncoderConfigurationOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioEncoderConfigurationOptionsResponse = { 
          //Options : { tt:AudioEncoder2ConfigurationOptions}
        //
        //};
        //return GetAudioEncoderConfigurationOptionsResponse;
      },

      //var GetMetadataConfigurationOptions = { };
      GetMetadataConfigurationOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetMetadataConfigurationOptionsResponse = { 
          //Options : { 
            //PTZStatusFilterOptions : { 
              //PanTiltStatusSupported : { xs:boolean},
              //ZoomStatusSupported : { xs:boolean},
              //PanTiltPositionSupported : { xs:boolean},
              //ZoomPositionSupported : { xs:boolean},
              //Extension : { }
            //},
            //Extension : { 
              //CompressionType : [{ xs:string}],
              //Extension : { }
            //}
          //}
        //
        //};
        //return GetMetadataConfigurationOptionsResponse;
      },

      //var GetAudioOutputConfigurationOptions = { };
      GetAudioOutputConfigurationOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioOutputConfigurationOptionsResponse = { 
          //Options : { 
            //OutputTokensAvailable : { xs:string},
            //SendPrimacyOptions : [{ xs:anyURI}],
            //OutputLevelRange : { 
              //Min : { xs:int},
              //Max : { xs:int}
            //}
          //}
        //
        //};
        //return GetAudioOutputConfigurationOptionsResponse;
      },

      //var GetAudioDecoderConfigurationOptions = { };
      GetAudioDecoderConfigurationOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioDecoderConfigurationOptionsResponse = { 
          //Options : { tt:AudioEncoder2ConfigurationOptions}
        //
        //};
        //return GetAudioDecoderConfigurationOptionsResponse;
      },

      //var GetVideoEncoderInstances = { 
        //ConfigurationToken : { xs:string}
      //
      //};
      GetVideoEncoderInstances : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetVideoEncoderInstancesResponse = { 
          //Info : { 
            //Codec : [{ 
              //Encoding : { xs:string},
              //Number : { xs:int}
            //}],
            //Total : { xs:int}
          //}
        //
        //};
        //return GetVideoEncoderInstancesResponse;
      },

      //var GetStreamUri = { 
        //Protocol : { xs:string},
        //ProfileToken : { xs:string}
      //
      //};
      GetStreamUri : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetStreamUriResponse = { 
          //Uri : { xs:anyURI}
        //
        //};
        //return GetStreamUriResponse;
      },

      //var StartMulticastStreaming = { };
      StartMulticastStreaming : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var StartMulticastStreamingResponse = { };
        //return StartMulticastStreamingResponse;
      },

      //var StopMulticastStreaming = { };
      StopMulticastStreaming : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var StopMulticastStreamingResponse = { };
        //return StopMulticastStreamingResponse;
      },

      //var SetSynchronizationPoint = { 
        //ProfileToken : { xs:string}
      //
      //};
      SetSynchronizationPoint : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetSynchronizationPointResponse = { };
        //return SetSynchronizationPointResponse;
      },

      //var GetSnapshotUri = { 
        //ProfileToken : { xs:string}
      //
      //};
      GetSnapshotUri : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetSnapshotUriResponse = { 
          //Uri : { xs:anyURI}
        //
        //};
        //return GetSnapshotUriResponse;
      },

      //var GetVideoSourceModes = { 
        //VideoSourceToken : { xs:string}
      //
      //};
      GetVideoSourceModes : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetVideoSourceModesResponse = { 
          //VideoSourceModes : { 
            //attributes : {
              //token : {tt:ReferenceToken},
              //Enabled : {xs:boolean}
            //},
            //MaxFramerate : { xs:float},
            //MaxResolution : { 
              //Width : { xs:int},
              //Height : { xs:int}
            //},
            //Encodings : { [xs:string]},
            //Reboot : { xs:boolean},
            //Description : { xs:string}
          //}
        //
        //};
        //return GetVideoSourceModesResponse;
      },

      //var SetVideoSourceMode = { 
        //VideoSourceToken : { xs:string},
        //VideoSourceModeToken : { xs:string}
      //
      //};
      SetVideoSourceMode : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetVideoSourceModeResponse = { 
          //Reboot : { xs:boolean}
        //
        //};
        //return SetVideoSourceModeResponse;
      },

      //var GetOSDs = { 
        //OSDToken : { xs:string},
        //ConfigurationToken : { xs:string}
      //
      //};
      GetOSDs : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetOSDsResponse = { 
          //OSDs : [{ 
            //attributes : {
              //token : {tt:ReferenceToken}
            //}
          //
            //VideoSourceConfigurationToken : { 
xs:string
            //},
            //Type : { xs:string},
            //Position : { 
              //Type : { xs:string},
              //Pos : { 
                //attributes : {
                  //x : {xs:float},
                  //y : {xs:float}
                //}
              //},
              //Extension : { }
            //},
            //TextString : { 
              //Type : { xs:string},
              //DateFormat : { xs:string},
              //TimeFormat : { xs:string},
              //FontSize : { xs:int},
              //FontColor : { 
                //attributes : {
                  //Transparent : {xs:int}
                //},
                //Color : { 
                  //attributes : {
                    //X : {xs:float},
                    //Y : {xs:float},
                    //Z : {xs:float},
                    //Colorspace : {xs:anyURI}
                  //}
                //}
              //},
              //BackgroundColor : { 
                //attributes : {
                  //Transparent : {xs:int}
                //},
                //Color : { 
                  //attributes : {
                    //X : {xs:float},
                    //Y : {xs:float},
                    //Z : {xs:float},
                    //Colorspace : {xs:anyURI}
                  //}
                //}
              //},
              //PlainText : { xs:string},
              //Extension : { }
            //},
            //Image : { 
              //ImgPath : { xs:anyURI},
              //Extension : { }
            //},
            //Extension : { }
          //}]
        //
        //};
        //return GetOSDsResponse;
      },

      //var GetOSDOptions = { 
        //ConfigurationToken : { xs:string}
      //
      //};
      GetOSDOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetOSDOptionsResponse = { 
          //OSDOptions : { 
            //MaximumNumberOfOSDs : { 
              //attributes : {
                //Total : {xs:int},
                //Image : {xs:int},
                //PlainText : {xs:int},
                //Date : {xs:int},
                //Time : {xs:int},
                //DateAndTime : {xs:int}
              //}
            //},
            //Type : { xs:string},
            //PositionOption : { xs:string},
            //TextOption : { 
              //Type : { xs:string},
              //FontSizeRange : { 
                //Min : { xs:int},
                //Max : { xs:int}
              //},
              //DateFormat : [{ xs:string}],
              //TimeFormat : [{ xs:string}],
              //FontColor : { 
                //Color : { },
                //Transparent : { 
                  //Min : { xs:int},
                  //Max : { xs:int}
                //},
                //Extension : { }
              //},
              //BackgroundColor : { 
                //Color : { },
                //Transparent : { 
                  //Min : { xs:int},
                  //Max : { xs:int}
                //},
                //Extension : { }
              //},
              //Extension : { }
            //},
            //ImageOption : { 
              //ImagePath : { xs:anyURI},
              //Extension : { }
            //},
            //Extension : { }
          //}
        //
        //};
        //return GetOSDOptionsResponse;
      },

      //var SetOSD = { 
        //OSD : { 
          //attributes : {
            //token : {tt:ReferenceToken}
          //}
        //
          //VideoSourceConfigurationToken : { 
xs:string
          //},
          //Type : { xs:string},
          //Position : { 
            //Type : { xs:string},
            //Pos : { 
              //attributes : {
                //x : {xs:float},
                //y : {xs:float}
              //}
            //},
            //Extension : { }
          //},
          //TextString : { 
            //Type : { xs:string},
            //DateFormat : { xs:string},
            //TimeFormat : { xs:string},
            //FontSize : { xs:int},
            //FontColor : { 
              //attributes : {
                //Transparent : {xs:int}
              //},
              //Color : { 
                //attributes : {
                  //X : {xs:float},
                  //Y : {xs:float},
                  //Z : {xs:float},
                  //Colorspace : {xs:anyURI}
                //}
              //}
            //},
            //BackgroundColor : { 
              //attributes : {
                //Transparent : {xs:int}
              //},
              //Color : { 
                //attributes : {
                  //X : {xs:float},
                  //Y : {xs:float},
                  //Z : {xs:float},
                  //Colorspace : {xs:anyURI}
                //}
              //}
            //},
            //PlainText : { xs:string},
            //Extension : { }
          //},
          //Image : { 
            //ImgPath : { xs:anyURI},
            //Extension : { }
          //},
          //Extension : { }
        //}
      //
      //};
      SetOSD : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetOSDResponse = { };
        //return SetOSDResponse;
      },

      //var CreateOSD = { 
        //OSD : { 
          //attributes : {
            //token : {tt:ReferenceToken}
          //}
        //
          //VideoSourceConfigurationToken : { 
xs:string
          //},
          //Type : { xs:string},
          //Position : { 
            //Type : { xs:string},
            //Pos : { 
              //attributes : {
                //x : {xs:float},
                //y : {xs:float}
              //}
            //},
            //Extension : { }
          //},
          //TextString : { 
            //Type : { xs:string},
            //DateFormat : { xs:string},
            //TimeFormat : { xs:string},
            //FontSize : { xs:int},
            //FontColor : { 
              //attributes : {
                //Transparent : {xs:int}
              //},
              //Color : { 
                //attributes : {
                  //X : {xs:float},
                  //Y : {xs:float},
                  //Z : {xs:float},
                  //Colorspace : {xs:anyURI}
                //}
              //}
            //},
            //BackgroundColor : { 
              //attributes : {
                //Transparent : {xs:int}
              //},
              //Color : { 
                //attributes : {
                  //X : {xs:float},
                  //Y : {xs:float},
                  //Z : {xs:float},
                  //Colorspace : {xs:anyURI}
                //}
              //}
            //},
            //PlainText : { xs:string},
            //Extension : { }
          //},
          //Image : { 
            //ImgPath : { xs:anyURI},
            //Extension : { }
          //},
          //Extension : { }
        //}
      //
      //};
      CreateOSD : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var CreateOSDResponse = { 
          //OSDToken : { xs:string}
        //
        //};
        //return CreateOSDResponse;
      },

      //var DeleteOSD = { 
        //OSDToken : { xs:string}
      //
      //};
      DeleteOSD : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var DeleteOSDResponse = { };
        //return DeleteOSDResponse;
      },

      //var GetMasks = { 
        //Token : { xs:string},
        //ConfigurationToken : { xs:string}
      //
      //};
      GetMasks : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetMasksResponse = { 
          //Masks : [{ 
            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //ConfigurationToken : { xs:string},
            //Polygon : { 
              //Point : [{ 
                //attributes : {
                  //x : {xs:float},
                  //y : {xs:float}
                //}
              //}]
            //},
            //Type : { xs:string},
            //Color : { 
              //attributes : {
                //X : {xs:float},
                //Y : {xs:float},
                //Z : {xs:float},
                //Colorspace : {xs:anyURI}
              //}
            //},
            //Enabled : { xs:boolean}
          //}]
        //
        //};
        //return GetMasksResponse;
      },

      //var GetMaskOptions = { 
        //ConfigurationToken : { xs:string}
      //
      //};
      GetMaskOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetMaskOptionsResponse = { 
          //Options : { 
            //attributes : {
              //RectangleOnly : {xs:boolean},
              //SingleColorOnly : {xs:boolean}
            //},
            //MaxMasks : { xs:int},
            //MaxPoints : { xs:int},
            //Types : { xs:string},
            //Color : { }
          //}
        //
        //};
        //return GetMaskOptionsResponse;
      },

      //var SetMask = { 
        //Mask : { 
          //attributes : {
            //token : {tt:ReferenceToken}
          //},
          //ConfigurationToken : { xs:string},
          //Polygon : { 
            //Point : [{ 
              //attributes : {
                //x : {xs:float},
                //y : {xs:float}
              //}
            //}]
          //},
          //Type : { xs:string},
          //Color : { 
            //attributes : {
              //X : {xs:float},
              //Y : {xs:float},
              //Z : {xs:float},
              //Colorspace : {xs:anyURI}
            //}
          //},
          //Enabled : { xs:boolean}
        //}
      //
      //};
      SetMask : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetMaskResponse = { };
        //return SetMaskResponse;
      },

      //var CreateMask = { 
        //Mask : { 
          //attributes : {
            //token : {tt:ReferenceToken}
          //},
          //ConfigurationToken : { xs:string},
          //Polygon : { 
            //Point : [{ 
              //attributes : {
                //x : {xs:float},
                //y : {xs:float}
              //}
            //}]
          //},
          //Type : { xs:string},
          //Color : { 
            //attributes : {
              //X : {xs:float},
              //Y : {xs:float},
              //Z : {xs:float},
              //Colorspace : {xs:anyURI}
            //}
          //},
          //Enabled : { xs:boolean}
        //}
      //
      //};
      CreateMask : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var CreateMaskResponse = { 
          //Token : { xs:string}
        //
        //};
        //return CreateMaskResponse;
      },

      //var DeleteMask = { 
        //Token : { xs:string}
      //
      //};
      DeleteMask : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var DeleteMaskResponse = { };
        //return DeleteMaskResponse;
      },

    }
  }
}
